#!/bin/bash

origin=$(pwd)
home=$(dirname $0)
cd $home

# clean
rm -r tmp 2>  /dev/null

# undeploy
rm -r tgt 2>  /dev/null

# compile
rsync -r src/* tmp

# deploy
mkdir tgt
cd tmp
zip -r ../tgt/[project.name].zip . 1> /dev/null
cd ..

# test
chmod 755 tst/tstr
tst/tstr
echo .

# redeploy

# use ...
cd $origin
