#!/bin/bash

function removeTargetIfExists ()
{
  if test -d "$tgt"
  then
    echo
    echo "removing $tgt"
    echo
    rm -r $(ls $tgt | sed "s|\(.*\)|$tgt/\1|")
  fi
}

home=$(dirname $0)
tgt=$1

if test -n "$tgt"
then
  removeTargetIfExists
  code -from $home/scm/tpt -with $home/scm/mpg -to "$tgt"
  recurser replace e "$tgt" "OPN" "["
  recurser replace e "$tgt" "CLS" "]"
  recurser replace e "$tgt" "__" " "
  chmod 755 "$tgt/build"
  "$tgt/build"
else
  code -from $home/scm/tpt -with $home/scm/mpg
  echo 'set-up coded'
fi
